# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Squirrel Planted!
email: hello@squirrelplanted.com
description: >- # this means to ignore newlines until "baseurl:"
  Food, farms, forests, and fungi
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo: "images/nasturtium_logo.png"
# Build settings
markdown: kramdown
remote_theme: "mmistakes/so-simple-theme"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

sass:
  sass_dir: ./_scss

# Required so we can search the node_modules
exclude:
  - node_modules

# Load environment variables
tokens:
  # I'd rather not check tokens in, but since this is going to be visible with requests in the browser
  # anyway and the token is scoped exclusively to the squirrelplanted domain I'm calling it ok.
  GOOGLE_PHOTOS_CLIENT_ID: 554268077783-eu92hc4cj658gau4souf4k8naaqb1vte.apps.googleusercontent.com

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"
plant_archive_path: "/plants/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# Collections
collections:
  plants:
    output: true
    permalink: /:collection/:path/
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: false
  # "Recipe" defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: false
      share: false

# Site Author
author:
  name: Ashleigh Baumgardner
  picture: /images/ashleigh_cauliflower.jpg
  email: ashleigh@squirrelplanted.com
  twitter: lashleigh
  links:
    - title: Twitter
      url: https://twitter.com/lashleigh
      icon: fab fa-twitter-square
    - title: Instagram
      url: https://instagram.com/llashleigh
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/lashleigh
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/lashleigh
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/llashleigh
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/lashleigh
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

